
DROP TABLE REPLY;
DROP TABLE BOARD_IMG;
DROP TABLE BOARD;
DROP TABLE BOARD_TYPE;

DROP TABLE CHAT_MESSAGE;
DROP TABLE CHAT_ROOM_JOIN;
DROP TABLE CHAT_ROOM;
DROP TABLE MEMBER;


DROP SEQUENCE SEQ_IMG_NO;
DROP SEQUENCE SEQ_CM_NO;
DROP SEQUENCE SEQ_CR_NO;
DROP SEQUENCE SEQ_UNO;
DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_RNO;

--------------------------------------------------
------------------  MEMBER     -------------------
--------------------------------------------------

CREATE TABLE MEMBER (
  USER_NO NUMBER PRIMARY KEY,               
  USER_ID VARCHAR2(30) NOT NULL UNIQUE,   
  USER_PWD VARCHAR2(100) NOT NULL,  
  USER_NAME VARCHAR2(15) NOT NULL,    
  -- NICK_NAME VARCHAR2(15) NOT NULL,    
  
  EMAIL VARCHAR2(100),        
  BIRTHDAY VARCHAR2(6),
  GENDER VARCHAR2(1) CHECK (GENDER IN('M', 'F')),    
  
  PHONE VARCHAR2(13),            
  ADDRESS VARCHAR2(100),
  ENROLL_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  PROFILE_IMG  VARCHAR2(200),  
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

CREATE SEQUENCE SEQ_UNO NOCACHE;

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', '관리자', 'MKM@naver.com' ,'540202' ,'M' ,  '010-1111-2222', '서울특별시', DEFAULT, DEFAULT, '' ,  DEFAULT);


----------------------------------------------------
-------------------- BOARD ????  --------------------
----------------------------------------------------

CREATE TABLE BOARD_TYPE(
  BOARD_CD CHAR(1) PRIMARY KEY,
  BOARD_NAME VARCHAR2(100) NOT NULL
);

INSERT INTO BOARD_TYPE
VALUES('N','일반게시판');

INSERT INTO BOARD_TYPE
VALUES('P','사진게시판');

CREATE TABLE BOARD(
  BOARD_NO NUMBER PRIMARY KEY,
  BOARD_TITLE VARCHAR2(100) NOT NULL,
  BOARD_CONTENT VARCHAR2(4000) NOT NULL,
  BOARD_CD CHAR(1) REFERENCES BOARD_TYPE,
  BOARD_WRITER NUMBER,
  COUNT NUMBER DEFAULT 0,
  CREATE_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
  FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER
);

CREATE SEQUENCE SEQ_BNO NOCACHE;


BEGIN
    FOR I IN 1..1000
    LOOP
        INSERT INTO BOARD VALUES 
        (SEQ_BNO.NEXTVAL , '일반게시글' || I , '게시글내용' || I,'N',1, DEFAULT, DEFAULT, DEFAULT);
    END LOOP;
END;
/

CREATE TABLE BOARD_IMG(
    BOARD_IMG_NO NUMBER PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(200),
    CHANGE_NAME VARCHAR2(200),
    REF_BNO VARCHAR2(200),
    IMG_LEVEL NUMBER(1)
);
CREATE SEQUENCE SEQ_IMG_NO NOCACHE; 
----------------------------------------------------
-------------------- REPLY  ---------------------	
----------------------------------------------------

CREATE TABLE REPLY(
  REPLY_NO NUMBER PRIMARY KEY,
  REPLY_CONTENT VARCHAR2(400),
  REF_BNO NUMBER,
  REPLY_WRITER NUMBER,
  CREATE_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (REF_BNO) REFERENCES BOARD,
  FOREIGN KEY (REPLY_WRITER) REFERENCES MEMBER
);

CREATE SEQUENCE SEQ_RNO NOCACHE;


COMMIT;



----------------------------------------------------
-------------------- CHAT  ---------------------	
----------------------------------------------------

CREATE TABLE CHAT_ROOM(
    CHAT_ROOM_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y',
    USER_NO NUMBER REFERENCES MEMBER
);

CREATE TABLE CHAT_MESSAGE(
    CM_NO NUMBER PRIMARY KEY,
    MESSAGE VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    CHAT_ROOM_NO NUMBER REFERENCES CHAT_ROOM,
    USER_NO NUMBER REFERENCES MEMBER
);

CREATE TABLE CHAT_ROOM_JOIN (
    USER_NO NUMBER REFERENCES MEMBER, 
    CHAT_ROOM_NO NUMBER REFERENCES CHAT_ROOM,
    PRIMARY KEY(USER_NO, CHAT_ROOM_NO)
);

CREATE SEQUENCE SEQ_CR_NO;
CREATE SEQUENCE SEQ_CM_NO;














